### ISSUE TITLE
Player kicked when using scroll in multiplayer

### ISSUE THREAD

**Issue by InsomniaKitten** [Darkhax-Minecraft/Enchanting-Plus#45]
Player is kicked with "Internal Server Error" message when trying to use a scroll on a multiplayer server. Client console shows now errors, however my server console spat this out. I'm using the [4.1.0.108](https://minecraft.curseforge.com/projects/enchanting-plus/files/2331837) release of the mod, and Forge version [12.18.1.2094](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.1.2094/forge-1.10.2-12.18.1.2094-changelog.txt)

`[02:31:24] [Server thread/WARN]: Failed to handle packet for /(my ip address)
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NoClassDefFoundError: net/darkhax/bookshelf/lib/util/RenderUtils
        at net.darkhax.eplus.item.ItemScroll.onUsingTick(ItemScroll.java:92) ~[ItemScroll.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2502) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1939) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
[02:31:24] [Server thread/INFO]: InsomniaKitten lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[02:31:24] [Server thread/INFO]: InsomniaKitten left the game
`

**Comment by darkhax** [comment]
This should be fixed in 4.1.0.112. Could you please confirm? (Requires an update to Bookshelf.)

**Comment by InsomniaKitten** [comment]
Updated to latest mod versions as instructed. Still getting similar issue. Here are the new server console messages.

[pastebin.com/e4uXi9xD](http://pastebin.com/e4uXi9xD)

**Comment by darkhax** [comment]
Not exactly, the issue is related to client/server code existing in the same class. Initially I had all particle code client side, however in the case of the scroll the particles are meant to be spawned from the server, this is the source of the original issue. The second issue is a result of me moving all particle code to a new class and forgetting to mark off some client side code. So when the class loader accessed the code, it was loading in all the unrelated client side code as well.

The fix for this issue has been tested and confirmed in [bookshelf](https://github.com/Darkhax-Minecraft/Bookshelf/commit/eb069cfbb86cf347cd523977f3d2b8ea9346c43e). You can get the new version [here](https://minecraft.curseforge.com/projects/bookshelf/files/2332251). If you run in to any more issues let me know.
